const AppConfig = {
  API: {
    CHECK_MOBILE_STATUS: 'getmobilenumberstatus',
    LOGIN_AUTH: 'LoginFromApp',
    SEND_OTP: 'forgetpassword',
    VERIFY_OTP: 'VerifyOTP',
    PASSWORD_RESET: 'forgetpasswordReset',
    CHANGE_PASSWORD: 'changePassword',
    VERSION_CHECK: 'VersionCheck',
    SENT_VIDEO_ENTIRE_COLLEGE: 'SendVideoToEntireCollege',
    SENT_VIDEO_PARTICULAR: 'SendVideoToParticularType',
    SENT_VIDEO_PARTICULAR_TUTOR: 'SendVideoToParticularTypeFromTutor',

    VIDEO_CONTENT_RESTRICTION: 'GetVideoContentRestriction',
    NOTICEBOARD_ENTIRE_COLLEGE_ADD: 'ManageNoticeBoard',
    NOTICEBOARD_ENTIRE_COLLEGE_ADD_TUTOR: 'ManageNoticeBoardFromTutor',

    NOTICEBOARD_DATA: 'GetNoticeListByType',
    DASHBOARD_DATA: 'DashboardApi',
    CIRCULAR_DATA: 'GetCircularListByType',
    ADD_CIRCULAR: 'SendImageOrPDFToParticularType',
    ADD_CIRCULAR_PARTICULAR_TYPE: 'SendImageOrPDFToParticularTypeWithCloudURL',
    ADD_CIRCULAR_PARTICULAR_TYPE_TUTOR: 'SendImageOrPDFToParticularTypeWithCloudURLFromTutor',

    ADD_CIRCULAR_ENTIRE_COLLEGE: 'SendImageOrPDFToEntireCollegeWithCloudURL',
    DELETE_CIRCULAR: 'DeleteCircular',
    FACULTY_LIST_OTHER: 'FacultyList',
    PRINCIPAL_FACULTU_LIST: 'FacultyListForprincipalloginSenderApp',
    STAFF_FACULTY_LIST: 'FacultyListForSenderApp',
    GET_GROUP_List_FOR_App: 'GetGrouplist',
    // COURSE_DEPT_LIST: 'CourseAndDepartmentListforApp',

    DIVISION_LIST: 'GetDivisions',
    GET_COURSE_DEPARTMENT: 'GetCoursesByDepartment',

    DEPARTMENT_DIV_LIST: 'GetDepartmentsbyDivision',
    GET_YEAR_LIST: 'GetYearListforApp',
    YEAR_SECTION_LIST: 'YearAndSectionListforApp',
    GET_SEM_AND_SECTIONS: 'semesterandsectionListforApp',
    GET_EXAM_LIST: 'GetExamListByType',
    GET_EXAM_LIST_SENDER: 'GetExamListByTypeforsenderapp',
    EXAM_CREATE: 'ExamCreation',
    GET_EXAM_DETAILS: 'GetDetailsForExamEdit',
    GET_SUBJECTS_EXAM_EDIT: 'GetSectionWiseSubjectListForExamEdit',
    GET_STUDENTS_MARKS: 'GetStudentMarkDetailsForApp',
    EDIT_DELETE_EXAM_API: 'EditSectionWiseExamForApp',
    ADD_EXAM_API: 'AddSectionInExamEditForApp',
    GET_ADS: 'GetAddsForCollege',
    ADS_CLICK: 'GetLogClickOnAdd',
    SUBJECT_SECTION_WISE: 'getsectionwisesubjectlist',
    GET_EVENTS_LIST: 'GetEventListByType',
    MANAGE_EVENTS: 'ManageEvents',
    MANAGE_EVENTS_TUTOR: 'ManageEventsFromTutor',

    ADD_EVENT_IMAGES: 'AddeventphotosWithCloudURL',
    ADD_VOICE_COMMUNICATION_ENTIRE_COLLEGE: 'SendFileToEntireCollege',
    ADD_VOICE_COMMUNICATION_PARTICULAR: 'SendFileToParticularType',
    ADD_VOICE_COMMUNICATION_PARTICULAR_TUTOR: 'SendFileToParticularTypeFromTutor',

    ADD_TEXT_COMMUNICATION_ENTIRE_COLLEGE: 'SendSMSToEntireCollege',
    ADD_TEXT_COMMUNICATION_PARTICULAR: 'SendSMSToParticularType',
    ADD_TEXT_COMMUNICATION_PARTICULAR_TUTOR: 'SendSMSToParticularTypeFromTutor',

    DELETE_TEXT: 'DeleteText',
    COMMUNICATION_DATA: 'GetCommunicationMessageBytype',
    GET_STAFF_DETAILS: 'GetstaffdetailsForApp',
    GET_STUDENT_CHAT: 'GetStudentChatScreenForApp',
    STUDENT_POST_QUESTION: 'StudentAskQuestionForApp',
    GET_STAFF_CLASS_DETAILS: 'GetStaffClassesforChatForApp',
    GET_STAFF_CHAT: 'GetStaffChatScreenForApp',
    BLOCK_STUDENT_FOR_APP: 'BlockStudentForApp',
    UNBLOCK_STUDENT_FOR_APP: 'UnblockStudentForApp',
    ANSWER_STUDENT_QUESTION: 'AnswerStudentQuestionForApp',
    GET_LEAVE_HISTORY_RECEPIENT: 'GetLeaveApplicationListForReceiverApp',
    GET_ATTENDANCE_FOR_PARENT: 'getattendanceforparent',
    SET_ATTENDANCE_FOR_STUDENTS: 'MarkAttendance',
    CHECK_ATTENDANCE_MARKING: 'CheckForAttendanceMarking',
    EDIT_ATTENDANCE_MARKING: 'Getlistforattendanceedit',
    GET_SUBJECT_LIST_FOR_STAFF: 'GetSubjectListforparticularstaff',
    GET_LEAVE_HISTORY_SENDER: 'GetLeaveApplicationListForSenderApp',
    GET_LEAVE_APPLY_STUDENT: 'ManageLeaveapplication',
    GET_LEAVE_TYPE: 'GetLeaveType',
    GET_APPROVE_LEAVE: 'ManageLeaveRequest',
    GET_ASSIGNMENT_LIST: 'GetAssignmentListByType',
    GET_SUBJECT_LIST: 'GetSubjectListforparticularstaff',
    GET_TUTOR_SUBJECT_LIST: 'GetClassListForTutor',

    POST_ASSIGNMENT: 'ManageAssignmentForText',
    POST_ASSIGNMENT_WITH_ATTACHMENT: 'ManageAssignmentWithCloudURL',
    GET_STUDENT_LIST: 'GetStudentListForApp',

    GET_MENTOR_STUDENT_LIST: 'GetMentorstudentListforapp',


    SUBMIT_ASSIGNMENT: 'SubmitAssignmentFromAppWithCloudURL',
    VIEW_ASSIGNMENT: 'ViewAssignmentContent',
    DELETE_ASSIGNMENT: 'AssignmentDelete',
    VIEW_SUMITTED_MEMEBER: 'GetAssignmentMemberCount',
    APP_READ_STATUS: 'Appreadstatus',
    GET_VIDEO_LIST: 'GetVideoList',
    GET_USER_MENU: 'GetUsermenu',
    UPDATE_FCM_TOKEN: 'DeviceToken',
    GET_NOTIFICATION_IN_APP: 'GetNotificationForCollege',

    GET_SUBJECT_DETAILS_FOR_SEM : 'GetSubjectDetailsForSemester',
    GET_PROFILE :'GetProfileDetails',
    
    GET_SEMESTER_LIST_FOR_COURSE : 'getsemesterlistforcourseid',
    GET_SEM_STUDENT_CREDIT : 'semesterwisestudentcreditdetails',
    GET_SEM_ALL_CREDIT : 'semesterwisestudentcreditdetailsall',
    GET_CATEGORY_LIST : 'getcategorylistforclgeid',
    GET_CATEGORY_STUDENT_CREDIT : 'categorywisestudentcreditdetails',

    GET_EXAM_APPLICATION_DETAILS : 'getExamApplicationDetails',


  },
  SCREEN: {
    NOTIFICATION: 'Notification',
    LOGIN_SCREEN: 'Login',
    CCOUNTRY_CHOOSE: 'CountryChoose',
    OTP_SCREEN: 'EnterOtp',
    FORGOT_SCREEN: 'SendOtp',
    RESET_PASSWORD_SCREEN: 'ResetPassword',
    CHANGE_NEW_PASSWORD: 'ChangeNewPassword',
    DASHBOARD: 'Dashboard',
    DASHBOARD_HOME: 'DashboardHome',
    HOME: 'Home',
    CHAT_HOME_SCREEN: 'Chat',
    CHAT_ROOM_SCREEN: 'ChatRoom',
    ADD_NOTICE_SCREEN: 'AddNotice',
    ADD_EXAM: 'AddExamScreen',
    ADD_EVENTS: 'AddEvents',
    ADD_CIRCULAR_SCREEN: 'AddCircular',
    ADD_LEAVE_SCREEN: 'AddLeave',
    ADD_VIDEO_SCREEN: 'VideoUploadScreen',
    ADD_VOICE: 'Add voice',
    ADD_MESSAGE: 'Add message',
    ASSIGNMENT: 'Assignment',
    ASSIGNMENT_PREVIOUS_SUBMISSION: 'AssignmentPreviousSubmission',
    STAFF_ASSIGNMENT: 'StaffAssignment',
    VIEW_ASSIGNMENT_SUBMISSION: 'ViewAssignmentSubmission',
    VIEW_ASSIGNMENT_QUESTION: 'viewAssignmentQuestion',
    NEW_ASSIGNMENT: 'NewAssignment',
    SUBMITTED_ASSIGNMENT: 'ViewSubmittedAssigmentScreen',
    COMMUNICATON: 'Communication',
    DETAILS_FOR_SEMESTER : 'Course Details',
    SEMESTER_CREDITS_SCREEN : 'Sem Credit Points',
    CATEGORY_CREDITS : 'Category Credit Points',
    EXAM_APPLICATION_DEATILS_SCREEN : 'Exam Application Details',

    PROFILE : 'Profile',
    EVENT_STACK: {
      NAME: 'EventStack',
      UPCOMING_EVENT: 'Upcoming Event',
      EVENTS_SCREEN: 'Events',
    },
    NOTICE_BOARD_STACK: {
      NAME: 'NoticeBoardStack',
    },
    CIRCULAR_STACK: {
      NAME: 'CircularStack',
    },
    EXAMINATION_STACk: {
      NAME: 'Examination',
    },
    COMMUNICATION_STACK: {
      NAME: 'Communication',
    },
    ATTENDANCE_STACK: {
      NAME: 'AttendanceScreen',
    },
  },
  VERSION_CODE : '13', //change version code for app upadte
  
  //API_URL: 'http://106.51.127.215:8090/api/AppDetailsBal/', //testing
  //API_URL: 'http://202.21.35.131:8091/api/AppDetailsBal/', //live testing db
   API_URL :'https://gradit.voicesnap.com/api/AppDetailsBal/',  //live
};

export default AppConfig;
